language: haskell

env:
  matrix:
    - GHCVER=8.2.2 CABALVER=2.0
    - GHCVER=8.4.3 CABALVER=2.2
    - GHCVER=8.6.5 CABALVER=2.4
    - GHCVER=8.8.1 CABALVER=3.0
    - GHCVER=head CABALVER=head
  global:
    - UBUNTU_PKGS="libgtk-3-dev libcairo2-dev"
    - EXTRA_DEPS_PRE="gtk2hs-buildtools"
    - HEAD_DEPS="diagrams-core diagrams-lib diagrams-cairo diagrams-svg diagrams-postscript diagrams-builder"

matrix:
  allow_failures:
    - env: GHCVER=head CABALVER=head

before_install:
  - git clone http://github.com/diagrams/diagrams-travis travis
  - source travis/scripts/set_env.sh
  - "echo 'constraints: transformers installed' >> cabal.config"
  - ./travis/scripts/before_install.sh

install: ./travis/scripts/install.sh

script: ./travis/scripts/script.sh

notifications:
  email: false
  irc:
    channels:
      - irc.freenode.org#diagrams
    skip_join: true
    template:
      - "\x0313diagrams-pandoc\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
