language: haskell

env:
  matrix:
    - GHCVER=7.6.3 CABALVER=1.18
    - GHCVER=7.8.4 CABALVER=1.18
    - GHCVER=7.10.2 CABALVER=1.22
    - GHCVER=head CABALVER=head
  global:
    - UBUNTU_PKGS="libgtk-3-dev libcairo2-dev"
    - EXTRA_DEPS_PRE="gtk2hs-buildtools"
    - HEAD_DEPS="diagrams-core diagrams-lib diagrams-cairo diagrams-svg diagrams-postscript diagrams-builder"
    - CABAL_FLAGS="--constraint=transformers\\\\ installed"

matrix:
  allow_failures:
    - env: GHCVER=head CABALVER=head

before_install:
  - git clone http://github.com/diagrams/diagrams-travis travis
  - source travis/scripts/set_env.sh
  - ./travis/scripts/before_install.sh

install: ./travis/scripts/install.sh

script: ./travis/scripts/script.sh

notifications:
  email: false
  irc:
    channels:
      - irc.freenode.org#diagrams
    skip_join: true
    template:
      - "\x0313diagrams-pandoc\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
